export const chatData = [
    {
      name: 'Aunt D',
      src: '',
      message: 'Not so much.',
      date: 'Saturday',
      seen: true,
    },
    {
      name: 'Fabian Orlu',
      src: '',
      message: 'Nope',
      date: 'Saturday',
      seen: false,
    },
    {
      name: 'Ee',
      src: '',
      message: 'I miss you',
      date: 'Saturday',
      seen: true,
    },
    {
      name: 'Steve',
      src: '',
      message: 'Sure thing!',
      date: 'Friday',
      seen: true,
    },
    {
      name: 'Tosin',
      src: '',
      message: 'Thanks a bunch',
      date: 'Friday',
      seen: true,
    },
    {
      name: 'Laila',
      src: '',
      message: 'Beautiful!',
      date: 'Saturday',
      seen: true,
    },
    {
      name: 'Drew',
      src: '',
      message: 'how was your meeting?',
      date: 'Thrusday',
      seen: false,
    },
    {
      name: 'Meenah Dave',
      src: '',
      message: 'See you soon.',
      date: 'Wednesday',
      seen: false,
    },
    {
      name: 'Agatha',
      src: '',
      message: 'Not yet',
      date: 'Tuesday',
      seen: false,
    },
    {
      name: 'Prince J',
      src: '',
      message: "Gotcha!",
      date: 'Tuesday',
      seen: true,
    },
    {
      name: 'Vera',
      src: '',
      message: '6 yards of it.',
      date: 'Monday',
      seen: true,
    },
    {
      name: 'Sammy',
      src: '',
      message: 'You can make it.',
      date: 'Sunday',
      seen: false,
    },
  ];